---
title: "Advanced example"
output: 
 html_document:
  toc: true
  toc_depth: 2
  toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 0, digits = 2)
```

#Load data and packages

```{r, message=F}
library(brms)
library(ggplot2)
library(bayesplot)
library(tidyverse)
library(kableExtra)
library(brmstools)
library(sjstats)
```

```{r}
#set up number of cores to use for fitting
n_cores <- parallel::detectCores()-1
```

```{r}
dat <- read.spss(paste("Steckler and Tracy Ginger Study 1.sav"),    
               to.data.frame = T, use.value.labels = F)

#add subject label
dat$subject <- seq(from = 100, by =1, length.out = 242)


#convert to long format
#only keep disgust ratings for now
dat %>% select(., subject, Condition, 
             last_meal_time, ends_with("disgust")) %>%
  gather(., item , rating, -subject, -Condition, -last_meal_time) %>%
  separate(., item, c("valence", "item"), extra="merge") -> d

dat[dat$valence=="med",]$valence <- "medium"
```


#Data visualization

